import type { SourceRecord } from "./types";

export const SOURCES: SourceRecord[] = [
  {
    id: "SRC-NEI-2024-CORNEAL-DYSTROPHIES",
    title: "Corneal Dystrophies",
    publisher: "National Eye Institute",
    url: "https://www.nei.nih.gov/eye-health-information/eye-conditions-and-diseases/corneal-conditions/corneal-dystrophies",
    type: "official_health",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Public patient-facing overview of major corneal dystrophy symptoms and treatment options.",
  },
  {
    id: "SRC-IC3D-2024",
    title: "IC3D Classification of Corneal Dystrophies — Edition 3 overview",
    publisher: "Die Ophthalmologie / Springer Nature",
    url: "https://link.springer.com/article/10.1007/s00347-024-02066-w",
    type: "peer_review",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Open-access overview of the 2024 third edition of the IC3D classification.",
  },
  {
    id: "SRC-GENEREVIEWS-CSCD",
    title: "Congenital Stromal Corneal Dystrophy",
    publisher: "GeneReviews / NCBI Bookshelf",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK2690/",
    type: "gene_database",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "GeneReviews entry covering DCN-related congenital stromal corneal dystrophy, surveillance, and genetic counseling.",
  },
  {
    id: "SRC-NCBI-GTR-EBMD",
    title: "Epithelial basement membrane dystrophy",
    publisher: "NIH Genetic Testing Registry",
    url: "https://www.ncbi.nlm.nih.gov/gtr/conditions/C0521723/",
    type: "gene_database",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "GTR condition page summarizing EBMD synonyms, inheritance entry, clinical features, and available tests.",
  },
  {
    id: "SRC-AAO-EYEWIKI-FUCHS",
    title: "Fuchs' Endothelial Dystrophy",
    publisher: "American Academy of Ophthalmology EyeWiki",
    url: "https://eyewiki.aao.org/Fuchs%E2%80%99_Endothelial_Dystrophy",
    type: "official_health",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Clinician-edited overview of Fuchs dystrophy and endothelial keratoplasty options.",
  },
  {
    id: "SRC-MAYO-FUCHS",
    title: "Fuchs dystrophy diagnosis and treatment",
    publisher: "Mayo Clinic",
    url: "https://www.mayoclinic.org/diseases-conditions/fuchs-dystrophy/diagnosis-treatment/drc-20352731",
    type: "official_health",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Patient-facing diagnosis and treatment summary, including DMEK/DSEK and future treatment research.",
  },
  {
    id: "SRC-MOORFIELDS-PK",
    title: "Corneal transplantation penetrating keratoplasty",
    publisher: "Moorfields Eye Hospital",
    url: "https://www.moorfields.nhs.uk/for-patients/information-hub/corneal-transplantation-penetrating-keratoplasty",
    type: "hospital_official",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Patient information on full-thickness corneal transplant benefits, risks, follow-up, and rejection symptoms.",
  },
  {
    id: "SRC-FUDAN-GEB101-2025",
    title: "全球首例角膜营养不良新一代基因疗法",
    publisher: "复旦大学上海医学院",
    url: "https://shmc.fudan.edu.cn/news/2025/0607/c1895a145723/page.htm",
    type: "official_news",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Hospital news on PTK combined with intrastromal TGFBI-targeted genome editing drug delivery in a first treated patient.",
  },
  {
    id: "SRC-GENEDITBIO-GEB101",
    title: "GEB-101 first patient dosed for TGFBI corneal dystrophy",
    publisher: "GenEditBio / PR Newswire",
    url: "https://www.prnewswire.com/news-releases/geneditbio-announces-first-patient-dosed-in-investigator-initiated-trial-of-geb101-worlds-first-in-vivo-crispr-cas-ribonucleoprotein-based-genome-editing-investigational-therapy-for-tgfbi-corneal-dystrophy-302475234.html",
    type: "clinical_trial",
    evidence_level: "C",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Company press release; useful for pipeline tracking but not a substitute for peer-reviewed clinical outcomes.",
  },
  {
    id: "SRC-ZOC-CORNEA",
    title: "角膜病科",
    publisher: "中山大学中山眼科中心",
    url: "https://www.gzzoc.org.cn/taxonomy/term/33",
    type: "hospital_official",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Official department page describing corneal transplant, endothelial transplant, keratoprosthesis, and complex ocular surface work.",
  },
  {
    id: "SRC-WZEYE-CORNEA",
    title: "角膜与眼表疾病中心",
    publisher: "温州医科大学附属眼视光医院",
    url: "https://www.wzeye.cn/doctorDepartment/27-1.html",
    type: "hospital_official",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Official center page describing corneal transplantation innovation, training base, and Chen Wei's team.",
  },
  {
    id: "SRC-SDEYE-XIELIXIN",
    title: "谢立信医生介绍",
    publisher: "山东第一医科大学附属青岛眼科医院",
    url: "https://www.sdeyei-h.edu/corneal_doctor/2019/pmbk5ezJ.html",
    type: "hospital_official",
    evidence_level: "A",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Official profile of Xie Lixin and the Shandong cornea program.",
  },
  {
    id: "SRC-PKU-ENDOTHELIAL-SUBSTITUTE",
    title: "北医三院开发生物可降解角膜内皮替代物",
    publisher: "北京大学新闻网",
    url: "https://news.pku.edu.cn/jxky/917883c345b54197946b314b9635b411.htm",
    type: "official_news",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Research news on corneal endothelial barrier mechanism and biodegradable endothelial substitute.",
  },
  {
    id: "SRC-TONGREN-CORNEA",
    title: "北京同仁医院眼角膜科",
    publisher: "北京同仁医院",
    url: "https://trhos.91health.net/Html/Departments/Main/Index_217.html",
    type: "hospital_official",
    evidence_level: "B",
    source_status: "blocked",
    verified_at: "2026-05-15",
    note: "Hospital-hosted department page found by search; automated fetch may be blocked, so details should be browser-verified before high-stakes use.",
  },
  {
    id: "SRC-BASCOM-CORNEA",
    title: "Corneal and External Diseases of the Eye",
    publisher: "Bascom Palmer Eye Institute",
    url: "https://www.bascompalmer.ae/speciality/corneal-and-external-diseases/",
    type: "hospital_official",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Public specialty page listing corneal dystrophy and corneal transplantation among treated conditions.",
  },
  {
    id: "SRC-WILMER-CORNEA",
    title: "Cornea, Cataract and External Disease",
    publisher: "Johns Hopkins Wilmer Eye Institute",
    url: "https://www.hopkinsmedicine.org/wilmer/services/cornea/",
    type: "hospital_official",
    evidence_level: "B",
    source_status: "blocked",
    verified_at: "2026-05-15",
    note: "Public service page for cornea disease and transplantation care; automated fetch returned 403, so browser verification is needed before high-stakes use.",
  },
  {
    id: "SRC-MASSEYE-CORNEA",
    title: "Cornea",
    publisher: "Mass Eye and Ear",
    url: "https://www.masseyeandear.org/specialties/cornea",
    type: "hospital_official",
    evidence_level: "B",
    source_status: "verified",
    verified_at: "2026-05-15",
    note: "Specialty page for cornea service and advanced keratoplasty procedures.",
  },
];

export function getSourceById(id: string) {
  return SOURCES.find((source) => source.id === id);
}
